### PR TITLE
Add constants for common errors

### PR DESCRIPTION
**Pull request by itaihanski**
## Related Issues

https://github.com/descope/etc/issues/4959

## Description

- Add constants for some of the most common errors. More can be added as needed.
- Updated README to show example usage

## Must

- [X] Tests
- [X] Documentation (if applicable)

### CODE REVIEW

**Review by meirwah — COMMENTED** [review]
missing test no ?

**Comment by itaihanski** [comment]
For constants?

**Review by shilgapira — DISMISSED** [review]

**Review by asafshen — APPROVED** [review]
👏

**Review by shilgapira — APPROVED** [review]

**Comment by meirwah** [comment]
> For constants?

at least for this part https://github.com/descope/node-sdk/pull/309/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R96

to make sure it doesn't break

**Pull request merged**
